# coding: utf-8

"""
    Daily Forecast API

    The daily forecast API returns the geocode weather forecasts for the current day up to the days duration in the API endpoint. The daily forecast product can contain multiple days of daily forecasts for each location. Each day of a forecast can contain up to (3) \"temporal segments\" meaning three separate forecasts. For any given forecast day we offer day, night, and a 24-hour forecast (daily summary).   • Standard HTTP Cache-Control headers are used to define caching length. The TTL value is provided in the HTTP Header as an absolute time value using the “Expires” parameter. Example:  “Expires: Fri, 12 Jul 2013 12:00:00 GMT”.   • REQUIRED: HEADER Accept-Encoding: gzip  • All requests to the API’s should request that the response be compressed. Supported encoding format is: gzip  • PLEASE NOTE: The Day object will no longer appear in the API after 3:00pm Local Apparent Time. At 3pm Local Apparent Time, we recommend that your application no longer displays the Day object.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.success_schema import SuccessSchema  # noqa: E501
from openapi_client.rest import ApiException

class TestSuccessSchema(unittest.TestCase):
    """SuccessSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SuccessSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.success_schema.SuccessSchema()  # noqa: E501
        if include_optional :
            return SuccessSchema(
                metadata = openapi_client.models.success_metadata_schema.SuccessMetadataSchema(
                    language = '0', 
                    transaction_id = '0', 
                    version = '0', 
                    latitude = 1.337, 
                    longitude = 1.337, 
                    units = '0', 
                    expire_time_gmt = 1.337, 
                    status_code = 56, ), 
                forecasts = [
                    openapi_client.models.forecast.forecast(
                        class = '0', 
                        expire_time_gmt = 1.337, 
                        fcst_valid = 1.337, 
                        fcst_valid_local = '0', 
                        num = 56, 
                        max_temp = 56, 
                        min_temp = 56, 
                        torcon = 56, 
                        stormcon = 56, 
                        blurb = '0', 
                        blurb_author = '0', 
                        lunar_phase_day = 56, 
                        dow = '0', 
                        lunar_phase = '0', 
                        lunar_phase_code = '0', 
                        sunrise = '0', 
                        sunset = '0', 
                        moonrise = '0', 
                        moonset = '0', 
                        qualifier_code = '0', 
                        qualifier = '0', 
                        narrative = '0', 
                        qpf = 1.337, 
                        snow_qpf = 1.337, 
                        snow_range = '0', 
                        snow_phrase = '0', 
                        snow_code = '0', )
                    ]
            )
        else :
            return SuccessSchema(
        )

    def testSuccessSchema(self):
        """Test SuccessSchema"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
